[package]
name = "rust-profiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
proc_macros = { version = "0.1.0", path = "proc_macros" }
